= SCRIPT_NAME(1)
:doctype: manpage
:author: Mark J. Jensen
:authorinitials: mjj
:mantitle: SCRIPT_NAME
:manname: SCRIPT_NAME
:manvolume: 1

== Name

SCRIPT_NAME - One line description of what the script does.

== Synopsis

*<SCRIPT_NAME>*
[*--input*=_input_file_ | *-i* _input_file_]
[*--output*=_output_file_ | *-o* _output_file_]
[*--help*]
[*--log*]
[*--quiet*]
[*--usage*]
[*--debug*]
[*--version*]
[*--verbose*]
[*--*]
[_input_file_ ...]

== Description

Copy *<SCRIPT_NAME>* into your new script file. Change *<SCRIPT_NAME>* to your new script name.
Update L<"/Synopsys"> and L<"/Options & Arguments"> section.

Remove sections that do not apply.

Write a detailed describe of the function of *<SCRIPT_NAME>*. What does it do?

May include numerous subsections (_i.e._, === head2, ==== head3, _etc._).

== Options & Arguments

=== Standard Options

[horizontal]

[*--input*=_input_file_ | *-i* _input_file_]:: If no input files are specified, _i.e._, *--input* or *-i*, the input is read from standard in, _STDIN_. Multiple input files are supported. If no input or output files are specified, *<SCRIPT_NAME>* copies _STDIN_ to _STDOUT_ much like cat. If no input file or _STDIN_ exists, *<SCRIPT_NAME>* exits gracefully with a exit code of 0.

[*--output*=_output_file_ | *-o* _output_file_]:: If no output file is specified, _i.e._, --output or -o, the output is written to _STDOUT_. If no input or output files are specified, *<SCRIPT_NAME>* copies _STDIN_ to _STDOUT_ much like cat. Do not use the same file as an input_file and as an output_file, see <<input_output_restriction,warning>>.

[*--help*]:: Print the help message to standard error, _STDERR_, and exit with an exit code of 0.

[*--log*]:: Log significant events to _STDERR_.

[*--quiet*]:: Only print fatal error messages to _STDERR_.

[*--usage*]:: Print the usage message to standard error, _STDERR_, and exit with an exit code of 0.

[*--debug*]:: Turn on the debug switch.

[*--version*]:: Print the version, copyright, and license message to standard error, _STDERR_, and exit with an exit code of 0.

[*--verbose*]:: Turn on the verbose switch.

[*`--`*]:: File list marker. The the double dash, `--`, on the command line signals the end options. The remaining items arguments,
even if some look like options.

[_input_files_]:: Additional input files.

== Exit Status

Exit Status Stuff

== Errors

A list of every error and warning message that the script can generate
(even the ones that will E<ldquo>never happenE<rdquo>), with a full explanation
of each problem, one or more likely causes, and any suggested remedies.

=== ZZZ9998X

routine: Error message

[horizontal]

Severity:: Fatal Error, Exit Code 16

Explanation:: Why was this error message generated.

System Action:: The system action depends upon the error conditions described in the accompanying messages.

User Response:: See the specific error message to determine the user action.

Programmer Response:: See the specific error message to determine the programmer action.

System Programmer Response:: See the specific error message to determine the system programmer action.


=== ZZZ9999X

routine: Error message

[horizontal]

Severity:: Fatal Error, Exit Code 16

Explanation:: Why was this error message generated.

System Action:: The system action depends upon the error conditions described in the accompanying messages.

User Response:: See the specific error message to determine the user action.

Programmer Response:: See the specific error message to determine the programmer action.

System Programmer Response:: See the specific error message to determine the system programmer action.

== Environment

=== Variables

No environmental variables were hurt during the development of this script.


== Dependencies

A list of all of the other scripts that this script relies upon, including any restrictions on versions, part of this script's distribution, or must be installed separately.

== Files

A list of the files that are used by this script.

== Input Files

=== _STDIN_

Describe the _STDIN_ input file format and content.

=== Other Input Files

Describe the other input files format and content.

== Output Files

=== _STDOUT_

Describe the _STDOUT_ output file format and content.

=== _STDERR_

Describe the _STDERR_ output file format and content.

=== Other Output Files

Describe the other output file format and content.

== Version

[cols="1,1,1,1", options="header"]
|===
| Version
| Author
| Description
| Date

| 0.0.1
| Mark J. Jensen
| 2025-99-99
| Initial Release

|===


== Security

NOTE: You must be the superuser to run this script.

WARNING: This script contains security info. Do not set world-readable. Better yet, redesign so that security information is not saved in your source code.

This script does not need root/superuser/administrator permission to function.

This script does not contain any security info.

== Standards

A list of the standards that this script complies with.

== Notes & Caveats

[#input_output_restriction]
WARNING: Input file and Output File Restriction

Do not use the same file as an input and output in the same command of *<SCRIPT_NAME>*. You will
destroy your data. *<SCRIPT_NAME>* checks for *--input* and *--output* being equal; however,
you should not do this in the first place.

[source,bash]
----
 <SCRIPT_NAME> --input=file_one >file_one
----


== Bugs

A list of all known bugs in the script, including any workarounds.

== Examples

Insert instructive examples here.

Multiple input files are valid, _e.g._,

[source,bash]
----
 <SCRIPT_NAME> -i file1 --input=file2 file3 file4 file5
----

A single output file is valid, _e.g._,

[source,bash]
----
 <SCRIPT_NAME> -i file1 -o output.file
----
]

== See Also

*ols_begin*


